### ISSUE TITLE
Bugs report

### ISSUE THREAD

**Issue by Smallpath** [autoboosh/jsxbin-to-jsx-converter#7] opened 2016-02-24 12:50 UTC
**Hello autoboosh**:

thanks for your nice work for decoding jsxbin

There are only `two` bugs that I found when I used jsxbin2jsx to decode my script
# The first 
Before encoding: 
```
(num/1).toString();
```
After decoding: 
```
num/1.toString();//Error
```
# The second
This is about escaped characters,causing error with variable name and image binary
```
var meta={ '\b':'\\b'} // After decoding, the name of variable is no longer '\b'
```
or
```
var str="\u00FF\u0009" //After decoding, this string becomes another string
```
# By the way
What is the license of jsxbin_to_jsx? I really want to create another javascript decoder based on the algorithm of your hard work,and just wonder if I could

**Comment by autoboosh** [comment] 2016-02-24 21:00
Thank you for those bug reports, I'll look into it.

The license is MIT, so you're free to create your own javascript decoder based on the same algorithm.

**Comment by autoboosh** [comment] 2016-02-25 20:30
The first should be fixed now. The output isn't always as pretty as it was before but it should work.

The second should be fixed now as well.

This:

`var str="\u00FF\u0009" //After decoding, this string becomes another string`

I'd say is expected behavior, since those are two unicode characters. The different string you see is actually the interpretation of these unicode characters. They are actually saved in the interpreted way in the JSXBIN file.

New release is up: https://github.com/autoboosh/jsxbin-to-jsx-converter/releases/tag/1.8.

Please report any problems you find. Thanks!

**Closed by autoboosh** 2016-02-25 20:30 UTC
